# Generated by Django 2.1.4 on 2019-02-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date',
            new_name='registerDate',
        ),
    ]
