# Generated by Django 2.1.4 on 2018-12-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='present',
            old_name='user_id',
            new_name='user',
        ),
    ]
