# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-18 13:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181215_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
