# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-18 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181218_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
