# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-18 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20181218_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='outTime',
            field=models.TimeField(null=True),
        ),
    ]
