# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-18 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20181218_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
