# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-21 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNo',
            field=models.CharField(max_length=12),
        ),
    ]
